Unit test fixes
51Degrees/device-detection-dotnet-examples pull request #62
Opened 2023-10-13 08:01 UTC by drasmart

### Changes:
- Add `org-name` to `workflows/nightly-prs-to-main.yml`.
- Make `device-detection-data` submodule URL relative.
- Clean up some project imports.
- Improve state description on `Cloud/GettingStarted-Web-ClientOnly/Pages/TestPage.cshtml` page.
- Reorder builder elements in `Cloud/GettingStarted-Web/appsettings.json` --- some tests (for yet unknown reason) fall back to injecting `ResourceKey` into element 0 (which was `UachJsConversionElement` instead of `CloudRequestEngine`).
- Make `ExampleUtils.IsInvalidKey` cause a warning instead of an error for `Examples.OnPremise.UpdateDataFile`.
- Make Selenium Web Driver initialize once per class rather than per test.
- Make `WebDriverTimeoutException` outcome inconclusive --- it is not the app's fault if the Selenium driver refuses connection (which has not been happening since driver became initialized once per test class, see above).
- Explicitly assert for "Unknown" browser detection result instead of expected proper major-minor-patch string.
- Handle errors thrown by [int.Parse](https://learn.microsoft.com/en-us/dotnet/api/system.int32.parse?view=net-7.0).
- Use [xUnit](https://xunit.net/) instead of `Microsoft.VisualStudio.TestTools.UnitTesting` for `GettingStartedTestBase` --- xUnit supports injecting `WebApplicationFactory` via `IClassFixture` _into_ the test class --- instead of having the test class _derive from_ `WebApplicationFactory`.
- Comment out hardware profiles IDs (from override test list) that are not properly handled by some engines (?) :
  + 124548 (OnPremise returns 15364)
  + 123083 (Cloud returns 0)
  + 108371 (Cloud returns 0)
  + 122591  (Cloud returns 0)
- Add `SupportsPropertyOverrides` to `GettingStartedTestOverrides.cs` and use it skip `VerifyExample_PropertyValue_Override` tests for OnPremise engine --- as it does not support these overrides (?).
- Update Selenium WebDriver and use relevant namespaces in code.
- Use `SetLoggingPreference` to see browser JS/console logs in test outputs.
- Drop `WebDriverManager` package --- Selenium now manages driver updates by itself.
- Add caching logic to `ci/fetch-assets.ps1`
- Use `dotnet` build method on Windows CI runners.
- Run unit tests on the solution instead of trying to launch test DLLs (which failed due to test cases trying to link to _executable_ targets).

2023-10-13 12:15 UTC, justadreamer requested changes

2023-10-13 14:57 UTC, drasmart commented on Examples/OnPremise/UpdateDataFile-Console/Program.cs
> +                if (ExampleUtils.IsInvalidKey(licenseKey))
The actual key is not logged.
The warning message would appear as
```
warn: FiftyOne.DeviceDetection.Examples.OnPremise.UpdateDataFile.Program.Example[0]
      The license key supplied (as the second command line argument to this program, or as an environment variable named 'DEVICEDETECTIONLICENSEKEY_DOTNET') is probably invalid.
```
![image](https://github.com/51Degrees/device-detection-dotnet-examples/assets/5711520/f52c8a87-ee90-459f-9640-c1cc309ae01a)

2023-10-23 12:21 UTC, drasmart commented on Examples/Cloud/GettingStarted-Web/appsettings.json
> +        // Our tests are dumb and require this element to be the first one.
The original order was restored, but the whole `PipelineOptions` section was moved to a separate JSON file.

2023-10-23 22:13 UTC, justadreamer approved these changes

2023-10-25 02:20 UTC, merged